version: 2
updates:
  # Node.js (npm) updates
  - package-ecosystem: "npm"  # Update Node.js dependencies using npm
    directory: "/visual_dashboard"  # Location of package.json and package-lock.json
    schedule:
      interval: "weekly"  # Check for updates every week
      day: "thursday"  # Run updates on Thursday
